management:
  server:
    servlet:
      context-path: /management
  endpoints:
    web:
      base-path: /application
      exposure:
        include:
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    context-path: /
  max-http-header-size: 12000
  port: 8930
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: poc